#!/usr/bin/env bash

PARSED_ARGUMENTS=$(getopt --long 'output-directory:,name:' -n 'make-screenshot' '' "$@")
VALID_ARGUMENTS=$?

if [ $VALID_ARGUMENTS -ne 0 ]; then
    echo 'Terminating...' >&2
    exit 1
fi

eval set -- "$PARSED_ARGUMENTS"

while true; do
    case "$1" in
        --output-directory)
            output_directory="$2"
            shift 2
            ;;
        --name)
            theme_name="$2"
            shift 2
            ;;
        --)
            shift
            break
            ;;
        *)
            echo "Unexpected option: $1"
            exit 1
            ;;
    esac
done

Xvfb :99 -screen 0 896x576x24 -nolisten tcp &
xvfb_pid="$!"

sleep 3

export DISPLAY=:99

echo "Creating screenshot in ${output_directory}"

emacs -Q --eval "(setq standard-output #'external-debugging-output)" \
    --eval '(message "Starting Emacs")' \
    --geometry 80x24 \
    --load /make-screenshot.el \
    --eval "(my-make-screenshot \"${theme_name}\" \"${GITHUB_WORKSPACE}/${output_directory}\")"

ls "${output_directory}"
kill "$xvfb_pid"
