#!/usr/bin/env bash

output_directory="$1"

Xvfb :99 -screen 0 896x576x24 -nolisten tcp &
xvfb_pid="$!"

sleep 3

export DISPLAY=:99

echo "Creating screenshot in ${output_directory}"

emacs -Q --eval "(setq standard-output #'external-debugging-output)" \
    --eval '(message "Starting Emacs")' \
    --geometry 80x24 \
    --load make-screenshot.el \
    --eval "(my-make-screenshot \"${output_directory}\")"

ls "${output_directory}"
kill "$xvfb_pid"
