on:
  push:
    paths-ignore:
    - 'screenshot.png'

jobs:
  take-screenshot:
    name: Update the screenshot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Take a screenshot
      uses: ./make-screenshot
      with:
        file-name: screenshot.png
        theme-name: yoshi
        width: 800
        height: 600
    - name: Commit screenshot
      run: |
        git config --global user.email "tom+screenshot@ryuslash.org"
        git config --global user.name "Screenshot maker"
        git add screenshot.png
        git commit -m "Update screenshot" && git push || echo no changes
