on:
  push:
    paths-ignore:
    - 'screenshot.png'
    - 'screenshots/**'

jobs:
  take-screenshot:
    name: Update the screenshot
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Take a screenshot
      uses: ./make-screenshot
      with:
        theme-name: yoshi
        width: 800
        height: 600
        script: showcase/showcase.el
    - name: Commit screenshot
      run: |
        git config --global user.email "tom+screenshot@ryuslash.org"
        git config --global user.name "Screenshot maker"
        git add screenshots
        git commit -m "Update screenshots" && git push || echo no changes
